config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'

  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      flash[:success] = 'Message が正常に投稿されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Message が投稿されませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      flash[:success] = 'Message は正常に更新されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Message は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @message.destroy

    flash[:success] = 'Message は正常に削除されました'
    redirect_to messages_url
  end

  private
  
  def set_message
    @message = Message.find(params[:id])
  end
    
  # Strong Parameter
  def message_params
    params.require(:message).permit(:content, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">MessageBoard</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to  '新規メッセージの投稿', new_message_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MessageBoard</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-xs-6">
    <%= form_for(message) do |f| %>
      <% if message.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% message.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, 'メッセージ' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>id: <%= @message.id %> のメッセージ編集ページ</h1>

<%= render 'form', message: @message %>

app/views/messages/index.html.erb
<h1>メッセージ一覧</h1>

<% if @messages.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>タイトル</th>
        <th>メッセージ</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td><%= link_to message.id, message %></td>
          <td><%= message.title %></td>
          <td><%= message.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @messages %>
  </div>
<% end %>

<%= link_to '新規メッセージの投稿', new_message_path, class: "btn-primary" %>

app/views/messages/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= render 'form', message: @message %>

app/views/messages/show.html.erb
<h1>id = <%= @message.id %> のメッセージ詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @message.id %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @message.title %></td>
  </tr>
  <tr>
    <th>メッセージ</th>
    <td><%= @message.content %></td>
  </tr>
</table>

<%= link_to 'このメッセージを編集する', edit_message_path(@message), class: 'btn btn-default' %>
<%= link_to 'このメッセージを削除する', @message, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>